package com.cloudhearing.android.lib_common.network.dataSource.racedetail

data class MatchInfo(
    val analystAdminUserId: String,
    val analystAdminUserName: String,
    val favoriteId: String,
    val hasFavorite: Boolean,
    val id: String,
    val leagueId: String,
    val leagueName: String,
    val matchDuration: Int,
    val matchTime: String,
    val matchType: String,
    val name: String,
    val playingField: String,
    val previewImageFilePath: String,
    val subType: String,
    val team1CoachFrontUserId: String,
    val team1CoachFrontUserName: String,
    val team1GroupId: String,
    val team1GroupName: String,
    val team1OrgLogoImagePath: String,
    val team1OrganizationId: String,
    val team1OrganizationName: String,
    val team1Score: Int,
    val team2CoachFrontUserId: String,
    val team2CoachFrontUserName: String,
    val team2GroupId: String,
    val team2GroupName: String,
    val team2OrgLogoImagePath: String,
    val team2OrganizationId: String,
    val team2OrganizationName: String,
    val team1BackgroundImagePath: String,
    val team2Score: Int,
    val uid: String
)