package com.cloudhearing.android.lib_common.network.dataSource.home.competition

data class Competition(
    val analystAdminUserId: String? = null,
    val analystAdminUserName: String? = null,
    val auditStatus: String? = null,
    val createBy: String? = null,
    val createTime: String? = null,
    val creatorName: String? = null,
    val dealStatus: String? = null,
    val id: String? = null,
    val matchDuration: Int? = null,
    val matchStatusName: String? = null,
    val matchTime: String? = null,
    val matchType: String? = null,
    val matchTypeName: String? = null,
    val name: String? = null,
    val playingField: String? = null,
    val previewImageFileId: String? = null,
    val previewImageFilePath: String? = null,
    val subType: String? = null,
    val team1CoachFrontUserId: String? = null,
    val team1CoachFrontUserName: String? = null,
    val team1GroupId: String? = null,
    val team1GroupName: String? = null,
    val team1OrgLogoImagePath: String? = null,
    val team1OrganizationId: String? = null,
    val team1OrganizationName: String? = null,
    val team1Score: Int? = null,
    val team2CoachFrontUserId: String? = null,
    val team2CoachFrontUserName: String? = null,
    val team2GroupId: String? = null,
    val team2GroupName: String? = null,
    val team2OrgLogoImagePath: String? = null,
    val team2OrganizationId: String? = null,
    val team2OrganizationName: String? = null,
    val team2Score: Int? = null,
    val uid: String? = null,
    val updateBy: String? = null,
    val updateTime: String? = null,
    val favoriteId: String? = null,
    val hasBooking: Boolean? = null,
    val favoriteType: String? = null,
    val eventName: String? = null,
    var isEditMode: Boolean = false,
    var isSelected: Boolean = false
) {

}